###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "Vicente",
    "password":"tulook"
}

###
GET http://localhost:9000/api/users HTTP/1.1
###
GET http://localhost:9000/api/users/Vicho HTTP/1.1